config/routes.rb
Rails.application.routes.draw do
  root to: 'snippets#index'
  resources :snippets, only: [:show, :new, :create]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  MAX_LENGTH = 8192

  validates :content, presence: true, length: { maximum: MAX_LENGTH }

  before_create :set_token_id

  scope :recent, -> { order(created_at: :desc) }

  def self.public
    where(private: false)
  end

  def to_param
    token_id
  end

  private

  def set_token_id
    self.token_id = SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  respond_to :html, :json

  def index
    @snippets = Snippet.recent.public.page(params[:page])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    @snippet.save
    respond_with @snippet
  end

  def show
    @snippet = Snippet.find_by!(token_id: params[:id])
  end

  private

  def snippet_params
    params.require(:snippet).permit(:content, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def snippet_summary(snippet)
    snippet.content.truncate_words(15)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/index.html.erb
<h1>Snippets</h1>
<%= link_to 'Create Snippet', new_snippet_path %>

<table class="snippets">
  <tbody>
    <% @snippets.each do |snippet| %>
      <tr><td><%= link_to snippet_summary(snippet), snippet %></td></tr>
    <% end %>
  </tbody>
</table>

<%= paginate @snippets %>

app/views/snippets/new.html.erb
<h1>Create your snippet</h1>
<%= form_for @snippet do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

<div class="nav">
  <%= link_to "Back", root_path %>
</div>

app/views/snippets/show.html.erb
<%= text_area_tag :snippet_content, @snippet.content %>

<%= label_tag :share_this %>
<%= text_field_tag :share_this, snippet_url(@snippet) %>

<div class="nav">
  <%= link_to "Back", root_path %>
</div>